apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: test-policy
  namespace: default
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ $.Values.tenant.name }}
                  labels:
                    k8s.ovn.org/primary-user-defined-network: ""

            - complianceType: musthave
              objectDefinition:
                apiVersion: user.openshift.io/v1
                kind: Group
                metadata:
                  name: {{ $.Values.tenant.name }}
                users:
                {{- range .Values.tenant.users }}
                  - {{ . }}
                {{- end }}

            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: admin-binding
                  namespace: {{ $.Values.tenant.name }}
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
                subjects:
                  - kind: Group
                    name: {{ $.Values.tenant.name }}

            - complianceType: musthave
              objectDefinition:
                apiVersion: k8s.ovn.org/v1
                kind: UserDefinedNetwork
                metadata:
                  name: {{ $.Values.tenant.name }}-udn
                  namespace: {{ $.Values.tenant.name }}
                spec:
                  layer2:
                    ipam:
                      lifecycle: Persistent
                    role: Primary
                    subnets:
                      - {{ $.Values.tenant.subnet }}
                  topology: Layer2

            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: {{ $.Values.tenant.name }}-quota
                  namespace: {{ $.Values.tenant.name }}
                spec:
                  hard:
                    pods: '1'
                    requests.cpu: '1'
                    requests.memory: 1Gi
                    limits.cpu: '2'
                    limits.memory: 2Gi

            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: testdeployment-{{ $.Values.tenant.name }}
                  namespace: {{ $.Values.tenant.name }}
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: testdeployment-{{ $.Values.tenant.name }}
                  template:
                    metadata:
                      labels:
                        app: testdeployment-{{ $.Values.tenant.name }}
                    spec:
                      containers:
                        - name: container-{{ $.Values.tenant.name }}
                          image: docker.io/appropriate/curl
                          command: ["sleep", "3600"]
                          resources:
                            requests:
                              cpu: "100m"
                              memory: "64Mi"
                            limits:
                              cpu: "200m"
                              memory: "128Mi"

            - complianceType: musthave
              objectDefinition:
                kind: HorizontalPodAutoscaler
                apiVersion: autoscaling/v2
                metadata:
                  name: hpa-{{ $.Values.tenant.name }}
                  namespace: {{ $.Values.tenant.name }}
                spec:
                  scaleTargetRef:
                    kind: Deployment
                    name: testdeployment-{{ $.Values.tenant.name }}
                    apiVersion: apps/v1
                  minReplicas: 1
                  maxReplicas: 3
                  metrics:
                    - type: Resource
                      resource:
                        name: memory
                        target:
                          type: AverageValue
                          averageValue: 250Mi
                  behavior:
                    scaleUp:
                      stabilizationWindowSeconds: 60
                      selectPolicy: Max
                      policies:
                        - type: Pods
                          value: 4
                          periodSeconds: 15
                        - type: Percent
                          value: 100
                          periodSeconds: 15
                    scaleDown:
                      stabilizationWindowSeconds: 120
                      selectPolicy: Max
                      policies:
                        - type: Pods
                          value: 4
                          periodSeconds: 60
                        - type: Percent
                          value: 10
                          periodSeconds: 60
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: test-policy-placement
  namespace: default
spec:
  clusterSets:
    - aws-tenant
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: test-policy-placement
  namespace: default
placementRef:
  name: test-policy-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: test-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy